// <auto-generated />
namespace SocialTap.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PutRequiretoDrink : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PutRequiretoDrink));
        
        string IMigrationMetadata.Id
        {
            get { return "201712060913289_PutRequiretoDrink"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
